var DD_roundies={ns:"DD_roundies",IE6:false,IE7:false,IE8:false,IEversion:function(){if(document.documentMode!=8&&document.namespaces&&!document.namespaces[this.ns])this.IE7=this.IE6=true;else if(document.documentMode==8)this.IE8=true},querySelector:document.querySelectorAll,selectorsToProcess:[],imgSize:{},createVmlNameSpace:function(){if(this.IE6||this.IE7)document.namespaces.add(this.ns,"urn:schemas-microsoft-com:vml");this.IE8&&document.writeln('<?import namespace="'+this.ns+'" implementation="#default#VML" ?>')},
createVmlStyleSheet:function(){var a=document.createElement("style");document.documentElement.firstChild.insertBefore(a,document.documentElement.firstChild.firstChild);if(a.styleSheet)try{var c=a.styleSheet;c.addRule(this.ns+"\\:*","{behavior:url(#default#VML)}");this.styleSheet=c}catch(d){}else this.styleSheet=a},addRule:function(a,c,d){if(typeof c=="undefined"||c===null)c=0;if(c.constructor.toString().search("Array")==-1)c=c.toString().replace(/[^0-9 ]/g,"").split(" ");for(var b=0;b<4;b++)c[b]=
!c[b]&&c[b]!==0?c[Math.max(b-2,0)]:c[b];if(this.styleSheet)if(this.styleSheet.addRule){a=a.split(",");for(b=0;b<a.length;b++)this.styleSheet.addRule(a[b],"behavior:expression(DD_roundies.roundify.call(this, ["+c.join(",")+"]))")}else{if(d){b=c.join("px ")+"px";this.styleSheet.appendChild(document.createTextNode(a+" {border-radius:"+b+"; -moz-border-radius:"+b+";}"));this.styleSheet.appendChild(document.createTextNode(a+" {-webkit-border-top-left-radius:"+c[0]+"px "+c[0]+"px; -webkit-border-top-right-radius:"+
c[1]+"px "+c[1]+"px; -webkit-border-bottom-right-radius:"+c[2]+"px "+c[2]+"px; -webkit-border-bottom-left-radius:"+c[3]+"px "+c[3]+"px;}"))}}else this.IE8&&this.selectorsToProcess.push({selector:a,radii:c})},readPropertyChanges:function(a){switch(event.propertyName){case "style.border":case "style.borderWidth":case "style.padding":this.applyVML(a);break;case "style.borderColor":this.vmlStrokeColor(a);break;case "style.backgroundColor":case "style.backgroundPosition":case "style.backgroundRepeat":this.applyVML(a);
break;case "style.display":a.vmlBox.style.display=a.style.display=="none"?"none":"block";break;case "style.filter":this.vmlOpacity(a);break;case "style.zIndex":a.vmlBox.style.zIndex=a.style.zIndex;break}},applyVML:function(a){a.runtimeStyle.cssText="";this.vmlFill(a);this.vmlStrokeColor(a);this.vmlStrokeWeight(a);this.vmlOffsets(a);this.vmlPath(a);this.nixBorder(a);this.vmlOpacity(a)},vmlOpacity:function(a){if(a.currentStyle.filter.search("lpha")!=-1){var c=a.currentStyle.filter;c=parseInt(c.substring(c.lastIndexOf("=")+
1,c.lastIndexOf(")")),10)/100;for(var d in a.vml)a.vml[d].filler.opacity=c}},vmlFill:function(a){if(a.currentStyle){var c=a.currentStyle;a.runtimeStyle.backgroundColor="";a.runtimeStyle.backgroundImage="";var d=c.backgroundColor=="transparent",b=true;if(c.backgroundImage!="none"||a.isImg){if(a.isImg)a.vmlBg=a.src;else{a.vmlBg=c.backgroundImage;a.vmlBg=a.vmlBg.substr(5,a.vmlBg.lastIndexOf('")')-5)}var g=this;if(!g.imgSize[a.vmlBg]){b=document.createElement("img");b.attachEvent("onload",function(){this.width=
this.offsetWidth;this.height=this.offsetHeight;g.vmlOffsets(a)});b.className=g.ns+"_sizeFinder";b.runtimeStyle.cssText="behavior:none; position:absolute; top:-10000px; left:-10000px; border:none;";b.src=a.vmlBg;b.removeAttribute("width");b.removeAttribute("height");document.body.insertBefore(b,document.body.firstChild);g.imgSize[a.vmlBg]=b}a.vml.image.filler.src=a.vmlBg;b=false}a.vml.image.filled=!b;a.vml.image.fillcolor="none";a.vml.color.filled=!d;a.vml.color.fillcolor=c.backgroundColor;a.runtimeStyle.backgroundImage=
"none";a.runtimeStyle.backgroundColor="transparent"}},vmlStrokeColor:function(a){a.vml.stroke.fillcolor=a.currentStyle.borderColor},vmlStrokeWeight:function(a){var c=["Top","Right","Bottom","Left"];a.bW={};for(var d=0;d<4;d++)a.bW[c[d]]=parseInt(a.currentStyle["border"+c[d]+"Width"],10)||0},vmlOffsets:function(a){for(var c=["Left","Top","Width","Height"],d=0;d<4;d++)a.dim[c[d]]=a["offset"+c[d]];c=function(g,e){g.style.left=(e?0:a.dim.Left)+"px";g.style.top=(e?0:a.dim.Top)+"px";g.style.width=a.dim.Width+
"px";g.style.height=a.dim.Height+"px"};for(var b in a.vml){d=b=="image"?1:2;a.vml[b].coordsize=a.dim.Width*d+", "+a.dim.Height*d;c(a.vml[b],true)}c(a.vmlBox,false);if(DD_roundies.IE8){a.vml.stroke.style.margin="-1px";typeof a.bW=="undefined"&&this.vmlStrokeWeight(a);a.vml.color.style.margin=a.bW.Top-1+"px "+(a.bW.Left-1)+"px"}},vmlPath:function(a){var c=function(h,f,j,i,k,l,n){var m=h?["m","qy","l","qx","l","qy","l","qx","l"]:["qx","l","qy","l","qx","l","qy","l","m"];k*=n;l*=n;f*=n;j*=n;i=i.slice();
for(var o=0;o<4;o++){i[o]*=n;i[o]=Math.min(f/2,j/2,i[o])}f=[m[0]+Math.floor(0+k)+","+Math.floor(i[0]+l),m[1]+Math.floor(i[0]+k)+","+Math.floor(0+l),m[2]+Math.ceil(f-i[1]+k)+","+Math.floor(0+l),m[3]+Math.ceil(f+k)+","+Math.floor(i[1]+l),m[4]+Math.ceil(f+k)+","+Math.ceil(j-i[2]+l),m[5]+Math.ceil(f-i[2]+k)+","+Math.ceil(j+l),m[6]+Math.floor(i[3]+k)+","+Math.ceil(j+l),m[7]+Math.floor(0+k)+","+Math.ceil(j-i[3]+l),m[8]+Math.floor(0+k)+","+Math.floor(i[0]+l)];h||f.reverse();return f.join("")};typeof a.bW==
"undefined"&&this.vmlStrokeWeight(a);var d=a.bW,b=a.DD_radii.slice(),g=c(true,a.dim.Width,a.dim.Height,b,0,0,2);b[0]-=Math.max(d.Left,d.Top);b[1]-=Math.max(d.Top,d.Right);b[2]-=Math.max(d.Right,d.Bottom);b[3]-=Math.max(d.Bottom,d.Left);for(var e=0;e<4;e++)b[e]=Math.max(b[e],0);e=c(false,a.dim.Width-d.Left-d.Right,a.dim.Height-d.Top-d.Bottom,b,d.Left,d.Top,2);c=c(true,a.dim.Width-d.Left-d.Right+1,a.dim.Height-d.Top-d.Bottom+1,b,d.Left,d.Top,1);a.vml.color.path=e;a.vml.image.path=c;a.vml.stroke.path=
g+e;this.clipImage(a)},nixBorder:function(a){for(var c=a.currentStyle,d=["Top","Left","Right","Bottom"],b=0;b<4;b++)a.runtimeStyle["padding"+d[b]]=(parseInt(c["padding"+d[b]],10)||0)+(parseInt(c["border"+d[b]+"Width"],10)||0)+"px";a.runtimeStyle.border="none"},clipImage:function(a){var c=DD_roundies;if(a.vmlBg&&c.imgSize[a.vmlBg]){var d=a.currentStyle,b={X:0,Y:0},g=function(h,f){var j=true;switch(f){case "left":case "top":b[h]=0;break;case "center":b[h]=0.5;break;case "right":case "bottom":b[h]=1;
break;default:if(f.search("%")!=-1)b[h]=parseInt(f,10)*0.01;else j=false}var i=h=="X";b[h]=Math.ceil(j?(a.dim[i?"Width":"Height"]-(a.bW[i?"Left":"Top"]+a.bW[i?"Right":"Bottom"]))*b[h]-c.imgSize[a.vmlBg][i?"width":"height"]*b[h]:parseInt(f,10));b[h]+=1};for(var e in b)g(e,d["backgroundPosition"+e]);a.vml.image.filler.position=b.X/(a.dim.Width-a.bW.Left-a.bW.Right+1)+","+b.Y/(a.dim.Height-a.bW.Top-a.bW.Bottom+1);e=d.backgroundRepeat;d={T:1,R:a.dim.Width+1,B:a.dim.Height+1,L:1};g={X:{b1:"L",b2:"R",d:"Width"},
Y:{b1:"T",b2:"B",d:"Height"}};if(e!="repeat"){d={T:b.Y,R:b.X+c.imgSize[a.vmlBg].width,B:b.Y+c.imgSize[a.vmlBg].height,L:b.X};if(e.search("repeat-")!=-1){e=e.split("repeat-")[1].toUpperCase();d[g[e].b1]=1;d[g[e].b2]=a.dim[g[e].d]+1}if(d.B>a.dim.Height)d.B=a.dim.Height+1}a.vml.image.style.clip="rect("+d.T+"px "+d.R+"px "+d.B+"px "+d.L+"px)"}},pseudoClass:function(a){var c=this;setTimeout(function(){c.applyVML(a)},1)},reposition:function(a){this.vmlOffsets(a);this.vmlPath(a)},roundify:function(a){this.style.behavior=
"none";if(this.currentStyle){var c=this.currentStyle;if({BODY:false,TABLE:false,TR:false,TD:false,SELECT:false,OPTION:false,TEXTAREA:false}[this.nodeName]!==false){var d=this,b=DD_roundies;this.DD_radii=a;this.dim={};var g={resize:"reposition",move:"reposition"};if(this.nodeName=="A"){a={mouseleave:"pseudoClass",mouseenter:"pseudoClass",focus:"pseudoClass",blur:"pseudoClass"};for(var e in a)g[e]=a[e]}for(var h in g)this.attachEvent("on"+h,function(){b[g[h]](d)});this.attachEvent("onpropertychange",
function(){b.readPropertyChanges(d)});e=function(j){j.style.zoom=1;if(j.currentStyle.position=="static")j.style.position="relative"};e(this.offsetParent);e(this);this.vmlBox=document.createElement("ignore");this.vmlBox.runtimeStyle.cssText="behavior:none; position:absolute; margin:0; padding:0; border:0; background:none;";this.vmlBox.style.zIndex=c.zIndex;this.vml={color:true,image:true,stroke:true};for(var f in this.vml){this.vml[f]=document.createElement(b.ns+":shape");this.vml[f].filler=document.createElement(b.ns+
":fill");this.vml[f].appendChild(this.vml[f].filler);this.vml[f].stroked=false;this.vml[f].style.position="absolute";this.vml[f].style.zIndex=c.zIndex;this.vml[f].coordorigin="1,1";this.vmlBox.appendChild(this.vml[f])}this.vml.image.fillcolor="none";this.vml.image.filler.type="tile";this.parentNode.insertBefore(this.vmlBox,this);this.isImg=false;if(this.nodeName=="IMG"){this.isImg=true;this.style.visibility="hidden"}setTimeout(function(){b.applyVML(d)},1)}}}};
try{document.execCommand("BackgroundImageCache",false,true)}catch(err$$1){}DD_roundies.IEversion();DD_roundies.createVmlNameSpace();DD_roundies.createVmlStyleSheet();
DD_roundies.IE8&&document.attachEvent&&DD_roundies.querySelector&&document.attachEvent("onreadystatechange",function(){if(document.readyState=="complete")for(var a=DD_roundies.selectorsToProcess,c=a.length,d=function(f,j,i){setTimeout(function(){DD_roundies.roundify.call(f,j)},i*100)},b=0;b<c;b++)for(var g=document.querySelectorAll(a[b].selector),e=g.length,h=0;h<e;h++)g[h].nodeName!="INPUT"&&d(g[h],a[b].radii,h)});